export const SERVICE_REPORT_MOCK_DATA = [
  {
    id: "1",
    currentDate: "2021-03-14",
    serviceMilage: "10000",
    visualLeaks: true,
    visualLeaksNote: "No leaks",
    looseBolts: false,
    checkForRust: false,
    checkForRustNote: "",
    engineOilChange: true,
    engineOilChangeNote: "Changed oil",
    oilFilterChange: true,
    oilFilterChangeNote: "Changed oil filter",
    airFilterChange: true,
    airFilterChangeNote: "Changed air filter",
    sparkPlugChange: true,
    sparkPlugChangeNote: "Changed spark plug",
    coolantChange: true,
    coolantChangeNote: "Changed coolant",
    fuelFilterChange: true,
    fuelFilterChangeNote: "Changed fuel filter",
    fuelInjectorChange: true,
    fuelInjectorChangeNote: "Changed fuel injector",
    clutchAdjust: true,
    clutchAdjustNote: "Adjusted clutch",
    transmissionFluidCheck: true,
    transmissionFluidCheckNote: "Checked transmission fluid",
    chainLubrication: true,
    chainLubricationNote: "Lubricated chain",
    sprocketInspection: true,
    sprocketInspectionNote: "Inspected sprocket",
    brakePadChange: true,
    brakePadChangeNote: "Changed brake pads",
    brakeFluidChange: true,
    brakeFluidChangeNote: "Changed brake fluid",
    tirePressureCheck: true,
    tirePressureCheckNote: "Checked tire pressure",
    tireChange: true,
    tireChangeNote: "Changed tire",
    forkOilChange: true,
    forkOilChangeNote: "Changed fork oil",
    rearShockInspection: true,
    rearShockInspectionNote: "Inspected rear shock",
    batteryVoltageCheck: true,
    batteryVoltageCheckNote: "Checked battery voltage",
    lightsTest: true,
    hornSwitchCheck: true,
    electricalIssuesNote: "No electrical issues",
    testRide: true,
    testRideNote: "Test ride completed",
    mechanicNote: "All good",
    nextServiceDate: "2021-03-14",
  },
];
