export const USERS_MOCK_DATA = [
  {
    id: "user1",
    uid: "gdOqPqycV9UjT5GAWjc2yUGNrus1",
    displayName: "",
    photoURL: "",
    role: "admin",
    status: "active",
    name: "John Doe",
    age: 30,
    email: "nikola.dj.87@gmail.com",
    password: 1234,
    phoneNumber: "+1234567890",
    address: "123 Main St",
    city: "New York",
    state: "NY",
    country: "USA",
    zipCode: "10001",
    motorcyclesOwned: ["1", "2"],
    motorcyclesInThePast: ["3"],
  },
];
